# Unet parameters
unet_config:
  dim: 64
  dim_mults: [1, 2, 4, 8]
  flash_attn: true

diffusion:
  image_size: 32
  timesteps: 1000           # number of steps
  sampling_timesteps: 250    # number of sampling timesteps

trainer:
  folder: "/scratch/work/sheshkr1/data/cifar10"
  train_batch_size: 32
  train_lr: 8e-5
  train_num_steps: 700000        # total training steps
  gradient_accumulate_every: 2    # gradient accumulation steps
  ema_decay: 0.995                # exponential moving average decay
  amp: true                       # turn on mixed precision
  calculate_fid: true              # whether to calculate fid during training